### PR TITLE
Added the secondary API

### PR DESCRIPTION
**Pull request by jigs1212**
Added secondary API to fetch the country name.

### CODE REVIEW

**Comment by stephin007** [comment]
@jigs1212 I just pulled your branch, its working as it should be 🤩 , But you did not check much of the css right? 😂

**Comment by jigs1212** [comment]
> @jigs1212 I just pulled your branch, its working as it should be  , But you did not check much of the css right?

Yes i did not change any css and not sure how the select box got large.

**Review by stephin007 — APPROVED** [review]
LGTM

**Comment by stephin007** [comment]
Thanks for working for the issue @jigs1212 🔥

**Pull request merged**
